#!/bin/bash

export package=pbladng


export PBLADNG_BUILDTIME=$(date +%Y.%m.%d-%H:%M:%S)
export PBLADNG_GOVERSION=$(go version | cut -d " " -f 3)
export PBLADNG_BUILDHOST=$(hostname)

export BASEDIR=/home/rphilips/go


platforms=( "linux/amd64"  )

for platform in "${platforms[@]}"
do
    echo $platform
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}

    basename=$package'-'$GOOS'-'$GOARCH

    cd /home/rphilips/go/brocade.be/base
    env GOOS=$GOOS GOARCH=$GOARCH go install ./...

    cd /home/rphilips/go/brocade.be/clipboard
    env GOOS=$GOOS GOARCH=$GOARCH go install

    cd /home/rphilips/go/brocade.be/pbladng/cli

    env PBLADNG_BUILDTIME=$PBLADNG_BUILDTIME PBLADNG_GOVERSION=$PBLADNG_GOVERSION GOOS=$GOOS GOARCH=$GOARCH PBLADNG_BUILDHOST=$PBLADNG_BUILDHOST go build -o /home/rphilips/go/brocade.be/pbladng/cli/$basename -ldflags "-X main.buildTime=$PBLADNG_BUILDTIME -X main.buildHost=$PBLADNG_BUILDHOST -X main.goVersion=$PBLADNG_GOVERSION" .

    echo /home/rphilips/go/brocade.be/pbladng/cli/$basename

done

rm /home/rphilips/bin/pblad
sudo mv /home/rphilips/go/brocade.be/pbladng/cli/pbladng-linux-amd64 /home/rphilips/bin/pblad
sudo chown rphilips:db /home/rphilips/bin/pblad


echo "/home/rphilips/bin/pblad"






